version: '3'
volumes:
  db-data:

services:
  flm-api:
    build: .
    restart: always
    container_name: flm-api
    volumes:
      - ./:/var/www/html
    ports:
      - 8097:80
    depends_on:
      - flm-mysql

  flm-mysql:
    image: mysql:8.0.29
    restart: always
    container_name: flm-mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 8098:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=flm-mysql
      - MYSQL_PORT=8098
      - MYSQL_DATABASE=flm
      - MYSQL_USER=flm
      - MYSQL_PASSWORD=flm
